version: "3.7"
services:
  jumpcloud-agent:
    build: .
    image: homecentr/jumpcloud-agent
    restart: unless-stopped
    volumes:
      - ./connect_key.txt:/connect_key.txt:ro
    environment:
      CONNECT_KEY_COMMAND: "cat /connect_key.txt"